name: poltry_farm
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_bloc: ^9.1.1

  intl: ^0.20.2

  equatable: ^2.0.7

  go_router: ^15.1.2

  cached_network_image: ^3.4.1

  flutter_svg: ^2.1.0

  loader_overlay: ^4.0.4+1

  intl_utils: ^2.8.10

  flutter_dotenv: ^5.2.1

  easy_infinite_pagination: ^0.0.6

  hive_ce: ^2.11.3

  path_provider: ^2.1.5

  accessibility_tools: ^2.6.0

  image_picker: ^1.1.2

  permission_handler: ^12.0.0+1

  firebase_core: ^3.14.0

  cloud_firestore: ^5.6.9

  firebase_database: ^11.3.7

  firebase_storage: ^12.4.7

  firebase_auth: ^5.6.0

  awesome_notifications_core: ^0.10.1

  awesome_notifications: ^0.10.1

  awesome_notifications_fcm: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  build_runner: ^2.4.14

  flutter_gen_runner: ^5.10.0

  hive_ce_generator: ^1.9.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - .env

flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  output_dir: lib/resources/l10n_generated

# Config gen assets
flutter_gen:
  output: lib/resources/assets_generated/ # Optional (default: lib/gen/)
  # Optional
  integrations:
    flutter_svg: true
