name: poltry_farm
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8 # iOS-style icons for Cupertino widgets

  flutter_bloc: ^9.1.1 # State management using the BLoC (Business Logic Component) pattern

  intl: ^0.20.2 # Internationalization and localization utilities (dates, numbers, etc.)

  equatable: ^2.0.7 # Simplifies value comparison between objects

  go_router: ^15.1.2 # Declarative routing for Flutter apps

  cached_network_image: ^3.4.1 # Displays images from the internet with caching support

  flutter_svg: ^2.1.0 # Renders SVG vector images in Flutter

  loader_overlay: ^4.0.4+1 # Easily show a loading overlay on top of the UI

  intl_utils: ^2.8.10 # Generates localization code from ARB files

  flutter_dotenv: ^5.2.1 # Loads environment variables from a `.env` file

  easy_infinite_pagination: ^0.0.6 # Simple infinite pagination support

  hive_ce: ^2.11.3 # Lightweight, fast local NoSQL database (Community Edition)

  path_provider: ^2.1.5 # Access commonly used locations on the filesystem

  image_picker: ^1.1.2 # Pick images from the gallery or camera

  permission_handler: ^12.0.0+1 # Request and check app permissions

  firebase_core: ^3.14.0 # Core Firebase initialization for Flutter

  cloud_firestore: ^5.6.9 # Cloud Firestore database access

  firebase_database: ^11.3.7 # Access to Firebase Realtime Database

  firebase_storage: ^12.4.7 # Upload and retrieve files from Firebase Storage

  firebase_auth: ^5.6.0 # Firebase authentication (email, Google, etc.)

  awesome_notifications_core: ^0.10.1 # Core for displaying local & push notifications

  awesome_notifications: ^0.10.1 # Full-featured local & push notifications for Android/iOS

  awesome_notifications_fcm: ^0.10.1 # Firebase Cloud Messaging integration for Awesome Notifications

dev_dependencies:
  flutter_test:
    sdk: flutter # Unit and widget testing support

  flutter_lints: ^4.0.0 # Recommended linter rules for Flutter projects

  build_runner: ^2.4.14 # Code generation tool used by many packages

  flutter_gen_runner: ^5.10.0 # Generates assets/constants from pubspec.yaml

  hive_ce_generator: ^1.9.2 # Code generator for Hive (CE)

  mockito: ^5.4.6 # Mocking library for unit tests

  accessibility_tools: ^2.6.0 # Accessibility testing tools

  bloc_test: ^10.0.0 # Testing utilities for BLoC state management

  coverage: ^1.6.3 # Collects test coverage reports

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/ # Folder for static assets (images, JSON, etc.)

flutter_intl:
  enabled: true
  arb_dir: lib/l10n # Directory for your ARB localization files
  output_dir: lib/resources/l10n_generated # Output location for generated localization code

# Config for asset generation
flutter_gen:
  output: lib/resources/assets_generated/ # Output location for generated asset references
  integrations:
    flutter_svg: true # Enable SVG support in generated assets
