name: poltry_farm
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_bloc: ^9.1.1

  intl: ^0.18.1

  equatable: ^2.0.7

  go_router: ^15.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/

flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  output_dir: lib/resources/l10n_generated

# Config gen assets
flutter_gen:
  output: lib/resources/assets_generated/ # Optional (default: lib/gen/)
  # Optional
  integrations:
    flutter_svg: true
