name: Dart Analyze

on:
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.1'

      - name: Install dependencies
        working-directory: poltry_farm
        run: flutter pub get

      - name: Run flutter analyze
        working-directory: poltry_farm
        run: flutter analyze
